style: use same style to minimise diff

diff --git a/entrypoint b/entrypoint
--- a/entrypoint
+++ b/entrypoint
@@ -4,13 +4,13 @@ set -e
 command_string="latexmk"
 
 case "$ACTION_FORMAT" in
-    pdf)
-        command_string="$command_string -pdf"
-        ;;
-    *)
-        echo "Invalid input for action argument: format (must be pdf)"
-        exit 1
-        ;;
+	pdf)
+		command_string="$command_string -pdf"
+	;;
+	*)
+		echo "Invalid input for action argument: format (must be pdf)"
+		exit 1
+	;;
 esac
 if [ ! "$ACTION_ARGS" = "" ]; then
     for arg in $ACTION_ARGS; do
@@ -18,8 +18,9 @@ if [ ! "$ACTION_ARGS" = "" ]; then
     done
 fi
 
-if [ "$ACTION_FILENAME" != "" ]; then
-    command_string="$command_string $ACTION_FILENAME"
+if [ -n "$ACTION_FILENAME" ]
+then
+	command_string="$command_string $ACTION_FILENAME"
 fi
 
 echo "Command: $command_string"
